[package]
name = "indoc"
version = "0.3.6"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Indented document literals"
repository = "https://github.com/dtolnay/indoc"
documentation = "https://docs.rs/indoc"
keywords = ["heredoc", "nowdoc", "multiline", "string", "literal"]
readme = "README.md"
edition = "2018"

[features]
unstable = ["indoc-impl/unstable"]

[dependencies]
indoc-impl = { version = "=0.3.6", path = "impl" }

[dev-dependencies]
rustversion = "1.0"
trybuild = { version = "1.0.19", features = ["diff"] }

[workspace]
members = ["impl", "unindent"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
